### ISSUE TITLE
Using Apply Model

### ISSUE THREAD

**Issue by swgeoscience** [gtkfi/ArcSDM#106]
Running in ArcGIS 10.5.1 on Windows 10 machine.

Unable to run the Apply Model in the experiemental toolbox. Generated models with both Random Forest and Support Vector Machine algorithms both fail with a long error that culminates in "Memory Error".

I have opened the script but cannot identify an obvious reason for the error at the given lines in the error message.

````
Start Time: Thu Aug 09 12:20:50 2018
Running script ApplyModel...
Parameters association
     Model          Rasters     
   b1_tin_ban       Layer_1     
   b2_tin_ban       Layer_2     
   b3_tin_ban       Layer_3     
   b4_tin_ban       Layer_4     
   b5_tin_ban       Layer_5     
   b6_tin_ban       Layer_6     
   b7_tin_ban       Layer_7     
   b8_tin_ban       Layer_8     
   b9_tin_ban       Layer_9     
   b10_tin_ba       Layer_10    
   b11_tin_ba       Layer_11    
   b12_tin_ba       Layer_12    
   b13_tin_ba       Layer_13    
Creating response raster...
Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\general_func.py", line 93, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 239, in execute
    create_response_raster(classifier, info_rasters, output_map, scale)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 125, in create_response_raster
    raster_array2 = np.empty([n_rows, n_cols, n_regr])
MemoryError


Traceback (most recent call last):
  File "<string>", line 923, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\general_func.py", line 93, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 239, in execute
    create_response_raster(classifier, info_rasters, output_map, scale)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 125, in create_response_raster
    raster_array2 = np.empty([n_rows, n_cols, n_regr])
MemoryError

Failed to execute (ApplyModel).
Failed at Thu Aug 09 12:21:59 2018 (Elapsed Time: 1 minutes 8 seconds)
````

**Comment by yeomo** [comment]
I changed the virtual memory but shouldn't be running out, I have 64 GB. I now have the more complex error:

```
Start Time: Wed Sep 12 17:30:06 2018
Running script ApplyModel...
Parameters association
     Model          Rasters     
   b1_tin_ban       Layer_1     
   b2_tin_ban       Layer_2     
   b3_tin_ban       Layer_3     
   b4_tin_ban       Layer_4     
   b5_tin_ban       Layer_5     
   b6_tin_ban       Layer_6     
   b7_tin_ban       Layer_7     
   b8_tin_ban       Layer_8     
   b9_tin_ban       Layer_9     
   b10_tin_ba       Layer_10    
   b11_tin_ba       Layer_11    
   b12_tin_ba       Layer_12    
   b13_tin_ba       Layer_13    
Creating response raster...
Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\general_func.py", line 93, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 239, in execute
    create_response_raster(classifier, info_rasters, output_map, scale)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 147, in create_response_raster
    responses = classifier.predict_proba(finite_array)[:, classifier.classes_ == 1]
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\ensemble\forest.py", line 578, in predict_proba
    X = self._validate_X_predict(X)
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\ensemble\forest.py", line 357, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\tree\tree.py", line 373, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\utils\validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
MemoryError


Traceback (most recent call last):
  File "<string>", line 923, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\general_func.py", line 93, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 239, in execute
    create_response_raster(classifier, info_rasters, output_map, scale)
  File "F:\ArcSDM\Toolbox\arcsdm\ApplyModel.py", line 147, in create_response_raster
    responses = classifier.predict_proba(finite_array)[:, classifier.classes_ == 1]
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\ensemble\forest.py", line 578, in predict_proba
    X = self._validate_X_predict(X)
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\ensemble\forest.py", line 357, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\tree\tree.py", line 373, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "C:\Python27\ArcGIS10.5\lib\site-packages\sklearn\utils\validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
MemoryError

Failed to execute (ApplyModel).
Failed at Wed Sep 12 17:30:58 2018 (Elapsed Time: 52.37 seconds)
```

It's still a memory error but is there a problem with either the validation or response raster?

**Comment by trotor** [comment]
Ok, it shouldn't be problem anymore (atleast I wouldn't expect anyone to
have any more for their gis workstations). What size are your rasters? I
think the size of the arrays is problem and calculating very large ones
requires some tweaking of code and/or tricks.

Are you running this on Pro or desktop?

**Comment by yeomo** [comment]
It is on Windows 10 Desktop using ArcMap 10.5.1

The raster size:
Col: 4001,
Row: 2226
Cell: 40 (meters)
Number of input bands in the composite raster: 13
441.67 MB in size (total)
NoData value -9999

I am happy to send example data if required.

Any help on tips or tricks would be much appreciated :) I have very basic python skills although advanced R user so could potentially be able to learn quickly!

**Comment by trotor** [comment]
I know some of our tools refuse to work on ArcGis pro but I am not sure
about this one.

Arcgis desktop is 32bit and I suspect its python env is 32bit too... Single
thread memory usage in windows is limited to 4gigabytes:
"*32*-*bit* processes use *32*-*bit* pointers, and 2^*32*=*4GB*. All the
*threads* share all their address space, otherwise you couldn't pass a
pointer from *one thread* to another. This limitation applies regardless of
PAE and regardless of how much physical*memory* you have. It is normally
2GB of address space for *32*-*bit*processes."


So there is slight possibility that this could be run on pro without memory
errors... Do you have pro to try it on?

**Comment by yeomo** [comment]
I have Pro now but this has generated more problems - I will comment on a more appropriate thread.

Hopefully I can come back to this one once the other issues are fixed >_<

**Comment by artolaiho** [comment]
ArcSDM Toolbox is now working at least ArcGIS Desktop 10.6.1, ArcGIS Pro 2.5 and ArcGIS Pro 2.6. The toolbox no longer has any ArcGIS Pro restrictions. If the problem persists, reopen this issue.
