### ISSUE TITLE
Failure of Get SDM Parameters

### ISSUE THREAD

**Issue by yeomo** [gtkfi/ArcSDM#109]
Hi,

I am probably doing something silly that I have forgotten but I have spent two days trying to get GWofE to work. It fails constantly and I think have tried a multitude of things...

```
Start Time: Fri Oct 05 11:48:56 2018
Running script GetSDMValues...

========== arcsdm values  ==========
                     ArcSdm 5.01.07 for ArcGis (Pro and Desktop)

Arcgis environment:  Desktop (10.5.1)
Workspace:           C:\Users\XXXX\test.gdb (LocalDatabase)
Scratch workspace:   C:\Users\XXXX\test.gdb (LocalDatabase)
Output coordinate system not set - defaulting mapunit to meter
Map Units:           meter
Mask:                "new_extent_1km_v1.img" and it is RasterLayer
  File "F:\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 122, in getMaskSize
    cellsize = float( str(arcpy.env.cellSize.replace(",",".")) )

  File "F:\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 222, in appendSDMValues
    gp.addMessage( "%-20s %s" %( "Mask size:", str(getMaskSize(mapUnits))  ));


Traceback (most recent call last):
  File "<string>", line 569, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 59, in execute
    appendSDMValues(gp,  Unitarea, TrainingSites)
  File "F:\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 222, in appendSDMValues
    gp.addMessage( "%-20s %s" %( "Mask size:", str(getMaskSize(mapUnits))  ));
  File "F:\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 122, in getMaskSize
    cellsize = float( str(arcpy.env.cellSize.replace(",",".")) )
ValueError: could not convert string to float: MAXOF

Failed to execute (GetSDMValues).
Failed at Fri Oct 05 11:48:58 2018 (Elapsed Time: 2.16 seconds)
```

I have made sure the mask is an integer raster and I have tried it with 0 =nodata and 1 =data. As well as nodata = nodata and 0 = data. 

Any help greatly appreciated.

**Comment by trotor** [comment]
You haven't set cell size to be explicitly something - in this case you
have left it to MAXOF, set it to whatever it is. I will later mark this as
improvement/bug. It does'nt at the moment like MAXOF value.

**Comment by yeomo** [comment]
Perfect, confirmed as working now.

Thanks!
