### ISSUE TITLE
GWofE workspace error

### ISSUE THREAD

**Issue by yeomo** [gtkfi/ArcSDM#110]
Running GWofE and possibly related to my other issue [109](https://github.com/gtkfi/ArcSDM/issues/109) causes this error.

I have set the workspace to a folder and a .gdb and I get the same error.

```
Executing: GrandWofe GWOFE_first_test WoE\woeFuzzyW1km.img;WoE\woeFuzzySn1km.img D;D resampled_training_data # 2 1
Start Time: Fri Oct 05 12:41:33 2018
Running script GrandWofe...

========== arcsdm values  ==========
                     ArcSdm 5.01.07 for ArcGis (Pro and Desktop)

Arcgis environment:  Desktop (10.5.1)
Workspace:           C:\Users\XXXX\WoE\1km_data\woeW_test_v1.gdb (LocalDatabase)
Scratch workspace:   C:\Users\XXXX\WoE\1km_data\woeW_test_v1.gdb (LocalDatabase)
Map Units:           meter
Mask:                "new_extent_1km_v1.img" and it is RasterLayer
Mask size:           6103.0
Cell Size:           1000
# Training Sites:    30
Unit Cell Area:      1.0km^2, Cells in area: 6103.0 
Prior Probability:   0.004916
Training Set:        C:\Users\XXXX\WOE\resampled_training_data.shp
Study Area Raster:   C:\Users\XXXX\WOE\new_extent_1km_v1.img
Study Area Area:     6103.0km^2
========== Starting GrandWofe ====================
Calculating weights for WoE\woeFuzzyW1km.img (d)...
GP ERRORS:


Failed to execute. Parameters are not valid.
ERROR 000840: The value is not a Workspace.
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).


PYTHON ERRORS:
Traceback Info:
  File "F:\ArcSDM\Toolbox\arcsdm\grand_wofe_lr.py", line 153, in execute
    Unit_Area__sq_km_, Missing_Data_Value)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: 

Failed to execute. Parameters are not valid.
ERROR 000840: The value is not a Workspace.
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).



Traceback (most recent call last):
  File "<string>", line 144, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\grand_wofe_lr.py", line 153, in execute
    Unit_Area__sq_km_, Missing_Data_Value)
  File "F:\ArcSDM\Toolbox\ArcSDM.pyt", line 615, in CalculateWeightsTool
ExecuteError: 

Failed to execute. Parameters are not valid.
ERROR 000840: The value is not a Workspace.
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).


Failed to execute (GrandWofe).
Failed at Fri Oct 05 12:41:45 2018 (Elapsed Time: 12.41 seconds)
```

I have also had an error which says that it could not create the table due invalid characters (ERROR:000340?) but cannot recreate this error.

Any help greatly appreciated!

**Comment by trotor** [comment]
Are your datasets in grouplayers ? They cause problems somewhere:

WoE\woeFuzzyW1km.img;WoE\woeFuzzySn1km.img

Ungroup them and try again. This could be marked improvement too if
that is the case.


T

**Comment by yeomo** [comment]
Thanks, extracting from group layers now generates the error I could not previously reproduce regarding invalid characters:

```
Executing: GrandWofe GWOFE_first_test woeFuzzySn1km.img;woeFuzzyW1km.img d;d resampled_training_data # 2 1
Start Time: Fri Oct 05 23:12:04 2018
Running script GrandWofe...

========== arcsdm values  ==========
                     ArcSdm 5.01.07 for ArcGis (Pro and Desktop)

Arcgis environment:  Desktop (10.5.1)
Workspace:           C:\Users\XXXX\WoE\1km_data\woeW_test_v1.gdb (LocalDatabase)
Scratch workspace:   C:\Users\XXXX\WoE\1km_data\woeW_test_v1.gdb (LocalDatabase)
Map Units:           meter
Mask:                "new_extent_1km_v1.img" and it is RasterLayer
Mask size:           6103.0
Cell Size:           1000
# Training Sites:    30
Unit Cell Area:      1.0km^2, Cells in area: 6103.0 
Prior Probability:   0.004916
Training Set:        C:\Users\XXXX\WoE\resampled_training_data.shp
Study Area Raster:   C:\Users\XXXX\WoE\new_extent_1km_v1.img
Study Area Area:     6103.0km^2
========== Starting GrandWofe ====================
Calculating weights for woeFuzzySn1km.img (d)...
GP ERRORS:


ERROR 000354: The name contains invalid characters
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).


PYTHON ERRORS:
Traceback Info:
  File "F:\ArcSDM\Toolbox\arcsdm\grand_wofe_lr.py", line 153, in execute
    Unit_Area__sq_km_, Missing_Data_Value)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: 

ERROR 000354: The name contains invalid characters
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).



Traceback (most recent call last):
  File "<string>", line 144, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\grand_wofe_lr.py", line 153, in execute
    Unit_Area__sq_km_, Missing_Data_Value)
  File "F:\ArcSDM\Toolbox\ArcSDM.pyt", line 615, in CalculateWeightsTool
ExecuteError: 

ERROR 000354: The name contains invalid characters
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).


Failed to execute (GrandWofe).
Failed at Fri Oct 05 23:12:14 2018 (Elapsed Time: 10.22 seconds)
```

**Comment by trotor** [comment]
That is amazing error... And XXXX in the above text is not replaced by you
for the sake of this message?

**Comment by yeomo** [comment]
The XXXX is replaced by me for privacy but it is a simple A-Z user. There are no special characters other than A-Z and 0-9 in the file path or file name and _ for spaces.

I can get a simple WoE (using separate tools) to work so there appears to be something in logistic regression causing the error?

**Comment by trotor** [comment]
I would be very keen to know what causes unwanted characters... will try
with similar setup someday but never noticed anything like that. Hopping to
get time for this ASAP

**Comment by trotor** [comment]
What happens if you run just the calculate weights tool with same inputs? There are some limitations how much information I get from the uderlying commands as python errors and I suppose the error comes from calculateweightstool, not wofe itself.

**Comment by yeomo** [comment]
Calculate Weights works perfectly on it's own (and as batch). I can generate a WoE model no problem using Calc Weights and Calc Response. I have just tested running the GWOFE as a model rather than a script and I get the same error.

**Comment by trotor** [comment]
One try: Could you experiment with shorter file names? It seems to add some extra letters to tmp tables and they could get too long causing something like this? It is very picky iirc

**Comment by trotor** [comment]
And please add empty file called DEBUG in the arcsdm directory to see some additional output from the script. Then rerun

**Comment by yeomo** [comment]
Adding a DEBUG file changes the error to this but does not write anything in DEBUG file...

```
Executing (Grand WOFE): GrandWofe GWOEtest woeG_v1.img;woeS_v1.img;woeW_v1.img d;d;d resampled_training_data true 3 1
Start Time: Thu Oct 11 11:36:34 2018
Running script GrandWofe...
Debug: F:\ArcSDM\toolbox\arcsdm.pyt

========== arcsdm values  ==========
                     ArcSdm 5.01.07 for ArcGis (Pro and Desktop)

Arcgis environment:  Desktop (10.5.1)
Workspace:           C:\Users\XXXX\WoE\1km_data (FileSystem)
Scratch workspace:   C:\Users\XXXX\WoE\1km_data (FileSystem)
Output coordinate system not set - defaulting mapunit to meter
Map Units:           meter
Mask:                "temp_mask_1km_v1.img" and it is RasterLayer
Mask size:           5976.0
Cell Size:           1000
# Training Sites:    30
Unit Cell Area:      1.0km^2, Cells in area: 5976.0 
Prior Probability:   0.005020
Training Set:        C:\Users\XXXX\resampled_training_data.shp
Study Area Raster:   C:\Users\XXXX\WoE\temp_mask_1km_v1.img
Study Area Area:     5976.0km^2

Debug: set local variables
Debug: [u'd', u'd', u'd']
Debug: [u'woeG_v1.img', u'woeS_v1.img', u'woeW_v1.img']
========== Starting GrandWofe ====================
Calculating weights for woeG_v1.img (d)...
Debug: Filename is a file - adding dbf
Debug:  Evidence raster layer name: woeG_v1.img
Debug:  Output table name: C:\Users\XXXX\WoE\1km_data\woeG_v1.img_GWOEtest_CD.dbf Exists already: 0
GP ERRORS:


ERROR 000354: The name contains invalid characters
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).


PYTHON ERRORS:
Traceback Info:
  File "F:\ArcSDM\Toolbox\arcsdm\grand_wofe_lr.py", line 153, in execute
    Unit_Area__sq_km_, Missing_Data_Value)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: 

ERROR 000354: The name contains invalid characters
Failed to execute (CreateTable).

Unhandled exception caught
Traceback (most recent call last):
  File "F:\ArcSDM\Toolbox\arcsdm\common.py", line 87, in execute_tool
    func(self, parameters, messages)
  File "F:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 621, in Calculate
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (CalculateWeightsTool).



Traceback (most recent call last):
  File "<string>", line 144, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\grand_wofe_lr.py", line 347, in execute
    print (msgs)
IOError: [Errno 9] Bad file descriptor

Failed to execute (Grand WOFE).
Failed at Thu Oct 11 11:36:48 2018 (Elapsed Time: 14.31 seconds)
```

I think the error may be because of the ".img" within the file "woeG_v1.img_GWOEtest_CD.dbf". Can you split the file string to remove file extension?

**Comment by trotor** [comment]
Expected to be fixed.
