### ISSUE TITLE
Area frequency table tool not working under WOFE (ArcSDM for 10.4 ).

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#136]
Area frequency table tool not working under WOFE (ArcSDM for 10.4 ).

\When processing, the tool keeps running even if left for 24hrs.

Kindly help with this

_Originally posted by @Tayyibriaz in https://github.com/gtkfi/ArcSDM/issues/118#issuecomment-699597413_

**Comment by tachyon-work** [comment]
Please provide a snapshot of the progress window so that we can see where it is stalling.

**Comment by Tayyibriaz** [comment]
On Monday, September 28, 2020, 12:51:44 AM GMT+5, tachyon-work <notifications@github.com> wrote:  
 
  tachyon-work (notifications@github.com) is not on your Guest List | Approve sender | Approve domain



Area frequency table tool not working under WOFE (ArcSDM for 10.4 ).

\When processing, the tool keeps running even if left for 24hrs.

Kindly help with this

Originally posted by @Tayyibriaz in #118 (comment)

**Comment by letter1225** [comment]
> Please provide a snapshot of the progress window so that we can see where it is stalling.

I have encountered some problem with this tool,  below is the traceback:
========== Starting area frequency ==========
Valuetype = 9.0
Floating Raster from Floating Raster Value: type F32

Traceback (most recent call last):
  File "<string>", line 674, in execute
  File "F:\wangjun\aftercluster\map3.5\ArcSDM-master\Toolbox\arcsdm\areafrequency.py", line 182, in Execute
    rasval = flt_ras[row.RASTERVALU]
  File "F:\wangjun\aftercluster\map3.5\ArcSDM-master\Toolbox\arcsdm\floatingrasterclass.py", line 131, in __getitem__
    return list(self.vat)[self.index(testValue)]
  File "F:\wangjun\aftercluster\map3.5\ArcSDM-master\Toolbox\arcsdm\floatingrasterclass.py", line 126, in index
    except ValueError ( msg):
NameError: global name 'msg' is not defined

**Comment by tachyon-work** [comment]
It looks like there's an issue with your input raster somewhere. The floatingrasterclass python error on line 131 of that script is looking for the vat file for the raster to pull info from and it's not finding what it's looking for.

Can you provide details on your input raster? i.e. file type? how was it created? what version of ArcGIS was it created in? etc.

**Comment by Tayyibriaz** [comment]
When i tried to use more than 10 rasters to make posterior probability this error showed. Less than 10 it is working 

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 19, 2020 at 8:10 AM, tachyon-work<notifications@github.com> wrote:    tachyon-work (notifications@github.com) is not on your Guest List | Approve sender | Approve domain



It looks like there's an issue with your input raster somewhere. The floatingrasterclass python error on line 131 of that script is looking for the vat file for the raster to pull info from and it's not finding what it's looking for.

Can you provide details on your input raster? i.e. file type? how was it created? what version of ArcGIS was it created in? etc.

**Comment by letter1225** [comment]
> It looks like there's an issue with your input raster somewhere. The floating rasterclass python error on line 131 of that script is looking for the vat file for the raster to pull info from and it's not finding what it's looking for.
> 
> Can you provide details on your input raster? i.e. file type? how was it created? what version of ArcGIS was it created in? etc.

Thank you.  Yes, I have changed the raster, and it worked. BTW,  sometimes the error was just caused by the name of raster file, symbols such as "-" are not allowed in the input raster name, change the name can sometimes solve the problem.
