### ISSUE TITLE
Error when executing : Calculate Weights ArcSDM-master

### ISSUE THREAD

**Issue by FilsCesar** [gtkfi/ArcSDM#142]
Executing: CalculateWeightsTool reclass_Kernel.img # "indices_d'or" Ascending E:\Ernestine\Master_Aristide\Modèle\kernel.dbf 1.96 0.002 -99 #
Start Time: Wed Jun  1 13:25:55 2022
Running script CalculateWeightsTool...
Reloaded arcsdm modules
Evidence Layer is reclass_Kernel.img and its data type is RasterLayer and coordinate system is WGS_1984_UTM_Zone_33N

========== arcsdm values  ==========
                     ArcSDM 5.03-1 for ArcGis (Pro and Desktop)

Arcgis environment:  Desktop (10.7.1)
  File "E:\Thèse\Outils\ArcSDM-master\Sentinel2\Toolbox\arcsdm\sdmvalues.py", line 203, in appendSDMValues
    gp.addmessage("%-20s %s (%s)" % ("Workspace: ", gp.workspace, desc.workspaceType));

'ascii' codec can't decode byte 0xe8 in position 53: ordinal not in range(128)
GPMEs: 0 
CW - PYTHON ERRORS:
Traceback Info:
  File "E:\Thèse\Outils\ArcSDM-master\Sentinel2\Toolbox\arcsdm\calculateweights.py", line 265, in Calculate
    arcsdm.sdmvalues.appendSDMValues(gp,  Unitarea, TrainingSites)

Error Info:
    <function format_exc at 0x0E611170>

Unhandled exception caught
Traceback (most recent call last):
  File "E:\Thèse\Outils\ArcSDM-master\Sentinel2\Toolbox\arcsdm\common.py", line 89, in execute_tool
    func(self, parameters, messages)
  File "E:\Thèse\Outils\ArcSDM-master\Sentinel2\Toolbox\arcsdm\calculateweights.py", line 265, in Calculate
    arcsdm.sdmvalues.appendSDMValues(gp,  Unitarea, TrainingSites)
  File "E:\Thèse\Outils\ArcSDM-master\Sentinel2\Toolbox\arcsdm\sdmvalues.py", line 203, in appendSDMValues
    gp.addmessage("%-20s %s (%s)" % ("Workspace: ", gp.workspace, desc.workspaceType));
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 53: ordinal not in range(128)

Completed script CalculateWeightsTool...
Failed to execute (CalculateWeightsTool).
Failed at Wed Jun  1 13:25:55 2022 (Elapsed Time: 0.20 seconds)

**Comment by FilsCesar** [comment]
Executing: CalculateWeights reclass_Kernel.img # "indices_d'or" Ascending E:\Ernestine\Master_Aristide\Modèle\Kernel_CA.dbf 1 0.00002 -99
Start Time: Wed Jun  1 14:01:11 2022
Running script CalculateWeights...
Workspace: C:\SDM\SDM
Scratch workspace: C:\Users\TEMP\Documents\ArcGIS\Default.gdb
PYTHON ERRORS:
Traceback Info:
  File "C:\SDM\SDM\Scripts\SDMValues.py", line 29, in appendSDMValues
    count += maskrow.count

Error Info:
    <type 'exceptions.RuntimeError'>: Row: Field count does not exist

GP ERRORS:
Executing: GetRasterProperties reclass_Kernel.img VALUETYPE #
Start Time: Wed Jun  1 14:01:11 2022
Value type = Unsigned Integer
Succeeded at Wed Jun  1 14:01:11 2022 (Elapsed Time: 0.02 seconds)

PYTHON ERRORS:
Traceback Info:
  File "C:\SDM\SDM\Scripts\NewWtsofEvIter.py", line 171, in <module>
    SDMValues.appendSDMValues(gp,  Unitarea, TrainingSites)

Error Info:
    <type 'exceptions.RuntimeError'>: Row: Field count does not exist

Failed script CalculateWeights...

Traceback (most recent call last):
  File "C:\SDM\SDM\Scripts\NewWtsofEvIter.py", line 171, in <module>
    SDMValues.appendSDMValues(gp,  Unitarea, TrainingSites)
  File "C:\SDM\SDM\Scripts\SDMValues.py", line 29, in appendSDMValues
    count += maskrow.count
RuntimeError: Row: Field count does not exist

Failed to execute (CalculateWeights).
Failed at Wed Jun  1 14:01:11 2022 (Elapsed Time: 0.16 seconds)

**Comment by em-t** [comment]
Calculate Weights has been updated for ArcGIS Pro 3.x, please check latest master branch and open a new issue if you are still experiencing the same issue.
