### ISSUE TITLE
Toolbox not working in ArcGis pro - Calculate Weights

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#34]
Parsing error: 
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 367
    if wtsrow.GetValue('class') <> MissingDataValue:
                                 ^
SyntaxError: invalid syntax

**Comment by trotor** [comment]
Fixed in ...15
