### ISSUE TITLE
"Mask" environment variable type in Training sites reduction

### ISSUE THREAD

**Issue by jtorppa** [gtkfi/ArcSDM#36]
The Mask variable is not allowed to be of a raster type in Training sites reduction tool. Polygon Mask works fine.

Error message, if raster:

Failed to execute. Parameters are not valid.
 ERROR 000840: The value is not a Feature Layer.
Failed to execute (MakeFeatureLayer).
-------------- END EXECUTION ---------------
Unhandled exception caught
Traceback (most recent call last):
  File "C:\ArcSDM\ArcSDM-master\Toolbox\arcsdm\sitereduction.py", line 49, in ReduceSites
    arcpy.MakeFeatureLayer_management(maskpolygon, maskname)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 5726, in MakeFeatureLayer
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 5723, in MakeFeatureLayer
    retval = convertArcObjectToPythonObject(gp.MakeFeatureLayer_management(*gp_fixargs((in_features, out_layer, where_clause, workspace, field_info), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
 ERROR 000840: The value is not a Feature Layer.
Failed to execute (MakeFeatureLayer).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ArcSDM\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\ArcSDM\ArcSDM-master\Toolbox\arcsdm\sitereduction.py", line 342, in ReduceSites
    raise arcpy.ExecuteError;
arcgisscripting.ExecuteError
Completed script SiteReductionTool...
Failed to execute (SiteReductionTool).
Failed at 29. toukokuuta 2017 13:01:59 (Elapsed Time: 11,49 seconds)

**Comment by trotor** [comment]
TODO: Verify if this is a problem in all of the tools?

**Comment by trotor** [comment]
This is "problem" or known restriction in selectbylocation tool needed by this item. 
Mask cannot be rasterlayer for this tool. Closing.
