### ISSUE TITLE
Calculate weights  crashes with Arcgis pro

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#53]
Roina/Johanna-hakemistossa on SDM_test.gdb kanta, jossa on 

studyarea_EUREF_1 (Mask ja Snap raster)
reclass_AEM_1 (input raster)

Start Time: 15. elokuuta 2017 15:44:54
Running script CalculateWeightsTool...
Reloaded arcsdm modules
name 'long' is not defined
GPMEs: 0
CW - PYTHON ERRORS:Traceback Info:  File "C:\ArcSDM\ArcSDM-master\Toolbox\arcsdm\calculateweights.py", line 210, in Calculate    MissingDataValue = long( parameters[7].valueAsText)Error Info:    <function format_exc at 0x0000000049487B70>
Unhandled exception caughtTraceback (most recent call last):  File "C:\ArcSDM\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool    func(self, parameters, messages)  File "C:\ArcSDM\ArcSDM-master\Toolbox\arcsdm\calculateweights.py", line 210, in Calculate    MissingDataValue = long( parameters[7].valueAsText)NameError: name 'long' is not defined
Completed script CalculateWeightsTool...
Failed to execute (CalculateWeightsTool).
Failed at 15. elokuuta 2017 15:44:54 (Elapsed Time: 0,31 seconds)

**Comment by trotor** [comment]
Most likely fixed in newest version. Waiting for input.

**Comment by trotor** [comment]
Was fixed.
