### ISSUE TITLE
Area Frequency Table error

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#60]
When running the Area Frequency Table the following error appears (this is with other that demo dataset)

========== Starting area frequency ==========
Valuetype = 9.0
Floating Raster from Floating Raster Value: type F32
Tsip
GP ERRORS:

PYTHON ERRORS:
Traceback Info:
  File "C:\ArcSDM_New\Toolbox\arcsdm\areafrequency.py", line 179, in Execute
    rasval = flt_ras[row.RASTERVALU]

Error Info:
    <type 'exceptions.NameError'>: global name 'msg' is not defined

Traceback (most recent call last):
  File "<string>", line 701, in execute
  File "C:\ArcSDM_New\Toolbox\arcsdm\areafrequency.py", line 179, in Execute
    rasval = flt_ras[row.RASTERVALU]
  File "C:\ArcSDM_New\Toolbox\arcsdm\floatingrasterclass.py", line 131, in __getitem__
    return self.vat.keys()[self.index(testValue)]
  File "C:\ArcSDM_New\Toolbox\arcsdm\floatingrasterclass.py", line 126, in index
    except ValueError ( msg):
NameError: global name 'msg' is not defined

Failed to execute (Area Frequency Table).
Failed at Sat Oct 07 13:21:18 2017 (Elapsed Time: 6,70 seconds)

**Comment by trotor** [comment]
Seems like you found new bug! Actually the "Error info" refers to error in error handling and this is most likely caused by new data type that didn't exist on demo data. Please send me the data and inputs to test this with and I'll take a look!

(You can attach files here too, zip it first)

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
