### ISSUE TITLE
Running the 'Calculate ROC Curves and AUC Values' in ArcGIS Pro Model Builder

### ISSUE THREAD

**Issue by maamiddleton** [gtkfi/ArcSDM#83]
Executing (Calculate ROC Curves and AUC Values): ROCTool VMS_deposits_train training_testing_points\VMS_nondeposits_test D:\mmiddlet3\aWORKmmiddlet\MPM\WP4\VMS_models\orig\origVMS_arcpro\origVMS_arcpro.gdb\origvmsout D:\mmiddlet3\aWORKmmiddlet\MPM\WP4\VMS_models\orig
Start Time: 26. helmikuuta 2018 13:47:11
Running script ROCTool...
Traceback (most recent call last):
  File "<string>", line 767, in execute
  File "D:\mmiddlet3\aPROGRAMSmmiddlet\ArcSDM5\ArcSDM-master (1)\ArcSDM-master\Toolbox\arcsdm\roctool.py", line 26, in execute
    positives_descr = arcpy.Describe(positives_param.valueAsText)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\__init__.py", line 1223, in Describe
    return gp.describe(value)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "VMS_deposits_train" does not exist
Failed to execute (Calculate ROC Curves and AUC Values).
Failed at 26. helmikuuta 2018 13:47:11 (Elapsed Time: 0,06 seconds)

My input 'Classification model' dat range was from -1 to 1, I rescaled it between 0 and 1 and still the tool did not work:
Executing (Calculate ROC Curves and AUC Values): ROCTool D:\mmiddlet3\aWORKmmiddlet\MPM\WP4\VMS_models\orig\origVMS_arcpro\origVMS_arcpro.gdb\VMS_deposits_train D:\mmiddlet3\aWORKmmiddlet\MPM\WP4\VMS_models\orig\origVMS_arcpro\origVMS_arcpro.gdb\VMS_nondeposits_test D:\mmiddlet3\aWORKmmiddlet\MPM\WP4\VMS_models\orig\origVMS_arcpro\origVMS_arcpro.gdb\Rescale_orig1 D:\mmiddlet3\aWORKmmiddlet\MPM\WP4\VMS_models\orig
Start Time: 26. helmikuuta 2018 13:59:45
Running script ROCTool...
Rescale_orig1: AUC = 0.936.
Traceback (most recent call last):
  File "<string>", line 767, in execute
  File "D:\mmiddlet3\aPROGRAMSmmiddlet\ArcSDM5\ArcSDM-master (1)\ArcSDM-master\Toolbox\arcsdm\roctool.py", line 89, in execute
    pylab.legend(plot_handles, legend_items, 4)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\matplotlib\pyplot.py", line 3560, in legend
    ret = gca().legend(*args, **kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\matplotlib\axes\_axes.py", line 548, in legend
    raise TypeError('Invalid arguments to legend.')
TypeError: Invalid arguments to legend.
Failed to execute (Calculate ROC Curves and AUC Values).
Failed at 26. helmikuuta 2018 13:59:47 (Elapsed Time: 1,64 seconds)

I have fixed the 'deposit' and 'non-deposits' to certain files.

What might be the problem?

Cheers, Maarit

**Comment by yeomo** [comment]
Is there any update to this issue? I have the same problem running in ArcGIS 10.5.1 on Windows 10.

It appears to be an issue drawing the plot and legend?

Any help much appreciated.

`Start Time: Fri Jul 13 13:58:23 2018
Running script ROCTool...
clip_tanKUratio01.tif: AUC = 0.337.

Traceback (most recent call last):
  File "<string>", line 735, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\roctool.py", line 89, in execute
    pylab.legend(plot_handles, legend_items, 4)
  File "C:\Python27\ArcGIS10.5\lib\site-packages\matplotlib\pyplot.py", line 3552, in legend
    ret = gca().legend(*args, **kwargs)
  File "C:\Python27\ArcGIS10.5\lib\site-packages\matplotlib\axes\_axes.py", line 548, in legend
    raise TypeError('Invalid arguments to legend.')
TypeError: Invalid arguments to legend.

Failed to execute (ROCTool).
Failed at Fri Jul 13 13:58:24 2018 (Elapsed Time: 0.50 seconds)`

**Comment by floodi** [comment]
ArcGIS 10.5.1 uses newer matplotlib that has an API change in legend-function. Should be fixed now.

**Comment by yeomo** [comment]
Confirmed, working now :) Many thanks!

**Comment by chinmay4896** [comment]
Hello I am facing same problem. Kindly help
